spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tPs6wLs7bCgF47pL1HN
      secret-key: Xiw61Wz5Zy4ZVyDu5CzO6MXzwWIcOO
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall724
  application:
    name: gulimall-third-party

server:
  port: 30000
